### ISSUE TITLE
is that working on Windows ?

### ISSUE THREAD

**Issue by namkazt** [c0i/cocos2dx-lite#1]
Hello @yinjimmy,

it's look like a really good project that focus only on 2D. is that working on Windows because as i see in readme windows is not supported

**Comment by yinjimmy** [comment]
I'm grad you're interested in this repo and I'm working on this.
Would you like to join this repo?

**Comment by namkazt** [comment]
sure, i'm interesting with only 2D features of cocos2d-x .This project will be good for me.

**Comment by namkazt** [comment]
@yinjimmy Hi,
How about dev plan and next features ?

**Comment by yinjimmy** [comment]
1. Separate Lua from cpp project (keep cpp project and lua project as cocos2d-x)
2. I want to have a package manager
3. More efficient audio engine
4. UI ?
5. ...

Do you have plan about improving 2d ?

**Comment by namkazt** [comment]
about 2D improment i want to add some : 
1. Dynamic Shadow Caster ( i think people want this feature )
2. Support Vector graphics like svg
3. Add support DragonBones ( there new build is really great with IK and mesh deform )
4. UI ? ( what do you want for UI - i like some quick and small like ImGui )
5. remake GUI for build app by python more easier ( command line is complicated )
6. ...

How can i contact with you directly ? do you have some chatting channel or some kind of this ?

**Comment by yinjimmy** [comment]
Invited you to slack.com ;)
