### ISSUE TITLE
Flatbuffers using ?

### ISSUE THREAD

**Issue by namkazt** [c0i/cocos2dx-lite#6]
I see cocos2d-x using Flatbuffers for some data and content. but how about we have a module that support user use Flatbuffers on proj ( easy way ).

like me. i have a lot of json content and Flatbuffers is a way to encrypt it.

**Comment by yinjimmy** [comment]
have restored Flatbuffers library

https://github.com/c0i/cocos2dx-lite/commit/f6b224c90db87d07f193d9bc13adae1ff54efab7
